# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

aliases:
  - &restore-cache-deps
      key: dependency-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}-2.1
  - &save-cache-deps
      key: dependency-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}-2.1
      paths:
        - node_modules

defaults: &defaults
  working_directory: ~/lit-ntml
  steps:
    - checkout
    - restore_cache: *restore-cache-deps
    - run:
        name: Install Global Dependencies
        command: sudo npm i -g npm@latest codecov@latest coveralls@latest --quiet
    - run:
        name: Install Dependencies
        command: npm ci --quiet
    - save_cache: *save-cache-deps
    - run:
        name: Versions
        command: node -v && npm version && which npm && pwd
    - run:
        name: Lint
        command: npm run lint
    - run:
        name: Build
        command: npm run build:test
    - run:
        name: Test
        command: npm run jest
    - run:
        name: Test Coverage
        when: on_success
        command: |
          cat ./coverage/lcov.info | coveralls
          cat ./coverage/lcov.info | codecov

jobs:
  node-v10:
    <<: *defaults
    docker:
      - image: circleci/node:10

  node-v12:
    <<: *defaults
    docker:
      - image: circleci/node:12

  node-v13:
    <<: *defaults
    docker:
      - image: circleci/node:13

workflows:
  version: 2
  multi-build-n-test:
    jobs:
      - node-v8
      - node-v10
      - node-v12
      - node-v13
