name: ci

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

defaults:
  run:
    shell: bash

env:
  IS_UBUNTU: false
  NODE_VERSION: v0.0.0
  NPM_CACHE_DIR: ~/.npm
  NPM_VERSION: 0.0.0

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, 'docs:') && !contains(github.event.head_commit.message, 'chore(release)')"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true
    env:
      IS_UBUNTU: ${{ contains(matrix.os, 'ubuntu') }}
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup node@${{ matrix.target }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.target }}

      # - name: Install latest npm
      #   run: |
      #     npm i -g npm@latest

      - name: List versions
        run: |
          echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV
          echo "NPM_CACHE_DIR=$(npm config get cache)" >> $GITHUB_ENV
          echo "NPM_VERSION=$(npm -v)" >> $GITHUB_ENV

          echo "${{ github.workflow }}-${{ github.ref || github.run_id }}"
          pwd
          ls -la
          which npm
          # npm x -y -- envinfo@latest

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v2
        with:
          # See this glob workaround at https://github.com/actions/toolkit/issues/713.
          path: |
            ${{ env.NPM_CACHE_DIR }}/*
            !${{ env.NPM_CACHE_DIR }}/_npx
          key: ${{ matrix.os }}-node-${{ env.NODE_VERSION }}-npm-${{ env.NPM_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ env.NODE_VERSION }}-npm-${{ env.NPM_VERSION }}

      - name: Install dependencies
        run: |
          npm ci
          sh $(npm root)/@reallyland/tools/list-npx-cache.sh

      - name: Lint
        run: |
          npm run lint:build

      - name: Benchmark
        run: |
          npm run bench -- --watch=false
