name: publish

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_VERSION: v0.0.0
  NPM_CACHE_DIR: ~/.npm
  NPM_VERSION: 0.0.0

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup node@${{ matrix.target }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.target }}
      #     registry-url: 'https://registry.npmjs.org'

      - name: List versions
        run: |
          echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV
          echo "NPM_CACHE_DIR=$(npm config get cache)" >> $GITHUB_ENV
          echo "NPM_VERSION=$(npm -v)" >> $GITHUB_ENV
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc

          pwd
          ls -la
          which npm
          npm config ls -l

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v3
        with:
          # See this glob workaround at https://github.com/actions/toolkit/issues/713.
          path: |
            ${{ env.NPM_CACHE_DIR }}/*
            !${{ env.NPM_CACHE_DIR }}/_npx
          key: ${{ matrix.os }}-node-${{ env.NODE_VERSION }}-npm-${{ env.NPM_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ env.NODE_VERSION }}-npm-${{ env.NPM_VERSION }}

      - name: Install dependencies
        run: |
          npm pkg delete scripts.postinstall
          npm ci

      - name: Lint
        run: |
          npm run lint:build

      - name: Build
        run: |
          npm run build

      - name: Cleanup package.json
        run: |
          npm pkg delete devDependencies nano-staged scripts

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: release package'
          publish: npm x -y -- changeset publish
          title: 'chore: release package'
          version: npm x -y -- changeset version
