name: ci

on:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-18.04]
        target: [13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node@${{ matrix.target }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.target }}
          registry-url: 'https://registry.npmjs.org'

      - name: List versions
        run: |
          node -v && npm -v && which npm

      - name: Install dependencies
        run: |
          npm ci --quiet

      - name: Publish to npm (RC)
        if: contains(github.ref, '-rc') == true
        run: |
          npm config list
          npm publish . --tag=next
        with:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: contains(github.ref, '-rc') == false
        run: |
          npm config list
          npm publish .
        with:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup node@${{ matrix.target }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.target }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GPR (RC)
        if: success() && contains(github.ref, '-rc') == true
        run: |
          npm config list
          npm publish . --tag=next
        with:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GPR
        if: success() && contains(github.ref, '-rc') == false
        run: |
          npm config list
          npm publish .
        with:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

